name: Azure Web App CI/CD

on:
  push:
    branches:
      - master   # ou main selon ta branche par défaut
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "azure-mern-dakar"    # Ton nom d'app Azure
  AZURE_WEBAPP_PACKAGE_PATH: "."            # racine du projet
  NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Install dependencies and build
      run: |
        npm install
        npm run build --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
