name: Deploy MERN to Azure WebApp

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: azure-mern-dakar
  AZURE_WEBAPP_PACKAGE_PATH: '.' # On déploie tout le projet
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du dépôt
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📁 Installer les dépendances serveur
        run: npm install

      - name: ⚛️ Installer les dépendances React et builder
        run: |
          cd client
          npm install
          npm run build

      - name: 📦 Upload build complet pour déploiement
        uses: actions/upload-artifact@v4
        with:
          name: full-app
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'

    steps:
      - name: 📥 Télécharger les fichiers de build
        uses: actions/download-artifact@v4
        with:
          name: full-app

      - name: 🚀 Déployer vers Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
