name: Deploy to Azure WebApp

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: azure-mern-dakar
  AZURE_WEBAPP_PACKAGE_PATH: './deploy'
  NODE_VERSION: '20.x'
  MONGO_URI: ${{ secrets.MONGO_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build --if-present
        working-directory: ./client

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy/client
          cp -r server.js routes package.json deploy/
          cp -r client/build deploy/client/

      - name: Create .env file for deployment
        run: |
          echo "MONGO_URI=${MONGO_URI}" >> deploy/.env
          echo "JWT_SECRET=${JWT_SECRET}" >> deploy/.env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

