name: Deploy MERN app to Azure WebApp

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: azure-mern-dakar
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies (backend)
        run: |
          npm install

      - name: Build React frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Prepare deployment package
        run: |
          rm -rf deploy
          mkdir -p deploy/client
          cp -r server.js routes package.json .env deploy/
          cp -r client/build deploy/client/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy

