name: Déployer sur Azure WebApp

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: azure-mern-dakar
  NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Installer les dépendances pour le serveur
        run: npm install

      - name: Build React client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Télécharger le package de déploiement
        run: |
          mkdir -p deploy/client
          cp -r server.js routes package.json deploy/
          cp -r client/build deploy/client/
        shell: bash

      - name: Upload deploy folder
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy folder
        uses: actions/download-artifact@v4
        with:
          name: deploy-package
          path: deploy

      - name: Déployer sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
